### PR TITLE
Feature/add appveyor

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 

On Appveyor:
* Ruby 2.4 hung
* Ruby 2.5 errored out

**Comment by ronaldtse** [comment]
@CAMOBAP795 AppVeyor still not working

**Comment by CAMOBAP** [comment]
@ronaldtse i know, there is problem with interference between ruby which comes from chocolatey and ruby installed by appveyor, Possible solution maybe to add --NoRuby param for our package which will skip ruby installation

**Comment by ronaldtse** [comment]
@CAMOBAP795 whatever way works 👍 

That said we need a fully functional Makefile.win -- some users need it. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse I have several questions:
 - is it possible/make sense to keep `appveyor.ps1`, `deploy.bat`, `deploy.sh`, `deploy_key.*`, `Makefile.*` in single place to be able reuse it (all of them or any of them)?
 - I need to configure `ENCRYPTION_LABEL` for appveyor

**Comment by ronaldtse** [comment]
@CAMOBAP795 we don't need to use AppVeyor to run the deploy script. I just want to know if the document builds under Windows. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse so `make -f Makefile.win clean all publish` will be enough, right?

**Comment by ronaldtse** [comment]
Yes 😉

**Comment by CAMOBAP** [comment]
@ronaldtse regarding keeping `appveyor.ps1` in some common place, are you ok if I will add it to https://github.com/metanorma/chocolatey-metanorma/ ?

**Comment by ronaldtse** [comment]
Is it a bit funny to add to the Chocolatey package? As long as it works...? But how can we keep it up to date with AppVeyor? e.g. they may change their packages and it won't work until next Chocolatey install?

**Comment by CAMOBAP** [comment]
@ronaldtse oh, let me clarify, I don't propose to add it to chocolatey package or create separate package, I just propose to use https://github.com/metanorma/chocolatey-metanorma/ to **host** `appveyor.ps1` script, nothing more

**Comment by ronaldtse** [comment]
How about this repo instead? https://github.com/metanorma/metanorma-document-gh-pages 😉

**Comment by ronaldtse** [comment]
Or... should there be a separate "metanorma-build-scripts" repo? What do you think?

**Comment by CAMOBAP** [comment]
@ronaldtse your proposal much better

**Comment by ronaldtse** [comment]
@camobap795 
https://github.com/metanorma/metanorma-build-scripts

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis 

Generally PR ready for review for now we have 2 problems:
 - temprally package install issue on travis
 - ruby23 crash on windows
```
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
	from C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect'
	from C:/Ruby23/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from C:/Ruby23/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from C:/Ruby23/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from C:/Ruby23/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/isobib-0.4.3/lib/isobib/scrapper.rb:181:in `get_page'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/isobib-0.4.3/lib/isobib/scrapper.rb:63:in `parse_page'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/isobib-0.4.3/lib/isobib/hit.rb:22:in `fetch'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/isobib-0.4.3/lib/isobib/iso_bibliography.rb:71:in `block in fetch_pages'
	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/iecbib-0.2.2/lib/iecbib/workers_pool.rb:18:in `block (2 levels) in worker'
```

Let me know if make sense to check windows ruby23 issue before proceed to next repository

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
