### PR TITLE
Update Makefile.win to be in sync with Makefile

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/metanorma-cli/issues/61

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 please feel free to merge when it works. Thanks!

**Comment by CAMOBAP** [comment]
partially blocked by https://github.com/metanorma/metanorma-linux-setup/pull/6

**Comment by CAMOBAP** [comment]
Something isn't right with original Makefile because it reports
"""
make: Nothing to be done for `all'.
"""

After `clean`

https://travis-ci.com/metanorma/ogc-tcpnp/jobs/198122254

@ronaldtse @opoudjis maybe you have an idea?

**Comment by ronaldtse** [comment]
It's because the document doesn't have the these lines:

```
= Title
...
:mn-document-class: ogc                   <===
:mn-output-extensions: xml,html,doc,pdf   <===
```

Can you add them to ogc-tcpnp.adoc?

**Comment by CAMOBAP** [comment]
@ronaldtse sure, on it

**Comment by ronaldtse** [comment]
@CAMOBAP795 Travis failed here

**Pull request merged**
